# Generated by Django 2.1.8 on 2019-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0002_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsForModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('data_type', models.CharField(choices=[('character', 'character'), ('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date')], editable=False, max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
