# Generated by Django 2.1.8 on 2019-04-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0004_instancetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid_model', models.UUIDField()),
            ],
        ),
        migrations.AlterField(
            model_name='fieldsformodel',
            name='data_type',
            field=models.CharField(choices=[('character', 'character'), ('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date'), ('json', 'json'), ('uuid', 'uuid')], editable=False, max_length=16),
        ),
    ]
