# Generated by Django 2.1.8 on 2019-05-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0006_registereddynamicmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('previous', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=20)),
            ],
        ),
    ]
