# Generated by Django 2.1.8 on 2019-05-11 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0007_allaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='allaction',
            name='changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
