# Generated by Django 2.1.8 on 2019-05-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0009_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereddynamicmodel',
            old_name='model_name',
            new_name='dynamic_model',
        ),
        migrations.AddField(
            model_name='registereddynamicmodel',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamo.Instance'),
        ),
        migrations.AddField(
            model_name='registereddynamicmodel',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
