# Generated by Django 2.1.8 on 2019-05-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0010_auto_20190516_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamo.RegisteredDynamicModel')),
            ],
        ),
    ]
